sudo: false

dist: trusty

language: php

php:
  - 7.3
  - 7.2
  - 7.1

before_script:
  - composer install --no-interaction

script:
  - composer cover
  - composer check-style

after_script:
  - composer coveralls
